"""
Multi-source Resonance V2.0 - 报告生成器

将 LLM 输出 + Layer 1 降维数据组合为完整的策略简报，
支持多格式导出：Markdown 文件、HTML 邮件、纯文本 Telegram 消息。
"""

import os
from datetime import datetime
from typing import Optional, Dict, Any
from pathlib import Path

from gateway.schemas import GatewayEnvelope
from llm_inference.response_parser import StrategyBriefing
from utils.logger import getLogger

logger = getLogger('llm.report_composer')


class ReportComposer:
    """策略简报生成器

    将 LLM 推理结果和 Layer 2 原始数据组合为完整报告，
    支持多格式输出和文件持久化。

    Attributes:
        output_dir: 报告输出目录
        branding: 报告品牌标记
    """

    def __init__(
        self,
        output_dir: str = "./reports",
        branding: str = "Multi-source Resonance V2.0",
    ):
        self.output_dir = output_dir
        self.branding = branding
        Path(output_dir).mkdir(parents=True, exist_ok=True)

    def compose_full_report(
        self,
        envelope: GatewayEnvelope,
        briefing: StrategyBriefing,
        pipeline_run_id: str = "",
    ) -> str:
        """生成完整的 Markdown 策略简报

        组合 Layer 2 数据摘要 + LLM 推理结果。

        Args:
            envelope: 网关信封
            briefing: 解析后的策略简报
            pipeline_run_id: 流水线运行 ID

        Returns:
            完整的 Markdown 报告文本
        """
        snapshot = envelope.snapshot
        now = datetime.now()

        # 幻觉警告
        hallucination_warning = ""
        if briefing.has_hallucination:
            hallucination_warning = (
                "\n> ⚠️ **HALLUCINATION WARNING**: The LLM output contains values "
                "inconsistent with the source JSON. Review flagged items:\n"
            )
            for flag in briefing.hallucination_flags:
                hallucination_warning += f"> - {flag}\n"
            hallucination_warning += "\n"

        # 数据质量警告
        quality_warning = ""
        if snapshot.data_quality_flag == "DEGRADED":
            quality_warning = (
                "\n> ⚠️ **Data Confidence: Reduced** — "
                f"Missing dimensions: {', '.join(snapshot.missing_dimensions)}\n"
            )
        elif snapshot.data_quality_flag == "ERROR":
            quality_warning = "\n> ❌ **DATA FEED ERROR** — Results may be unreliable\n"

        report = f"""# {self.branding} — Daily Strategy Briefing

**Date**: {now.strftime('%Y-%m-%d')}
**Asset**: {snapshot.underlying_asset}
**Pipeline Run**: `{pipeline_run_id[:8] if pipeline_run_id else 'N/A'}...`
**Generated**: {now.strftime('%Y-%m-%d %H:%M:%S UTC')}
**Schema Version**: {envelope.schema_version}
{quality_warning}
---

## 📊 Resonance Summary

| Metric | Value |
|--------|-------|
| Resonance Score | **{snapshot.resonance_intensity_score}/100** ({snapshot.resonance_signal_state}) |
| Data Quality | {snapshot.data_quality_flag} |
| Available Dimensions | {snapshot.available_dimensions}/4 |

---

## 🎯 Key Levels

| Level | Price | Strength |
|-------|-------|----------|
| Gamma Flip | {snapshot.gamma_flip_level} | Proximity: {snapshot.gamma_flip_proximity_pct:+.2f}% |
| Core Support | {snapshot.core_support_wall} | {snapshot.support_wall_strength} |
| Core Resistance | {snapshot.core_resistance_wall} | — |

---

{hallucination_warning}
## 🤖 LLM Strategy Analysis

{briefing.full_text if briefing.full_text else '_No LLM analysis available_'}

---

## 📋 Source Data Reference

| Dimension | Key Metric |
|-----------|------------|
| GEX | Regime: {snapshot.net_gamma_regime}, Pct: {snapshot.gex_percentile}% |
| Dark Pool | DIX: {snapshot.dark_pool_dix_status}, {snapshot.dark_pool_accumulation_regime}, Pct: {snapshot.dix_percentile}% |
| VIX | {snapshot.vix_term_structure_state}, Panic: {snapshot.vix_panic_premium_pct:+.2f}%, Vanna: {snapshot.vanna_exposure_bias} |
| Crypto | {snapshot.crypto_leverage_state}, OI: {snapshot.crypto_oi_change_pct:+.2f}% |
| Hawkes | {snapshot.hawkes_branching_state}, Ratio: {snapshot.hawkes_branching_ratio:.2f} |

---

*Generated by Multi-source Resonance V2.0 — Three-Layer Decoupled Architecture*
*Layer 1 (Math Engine) → Layer 2 (JSON Gateway) → Layer 3 (LLM Inference)*
"""
        logger.info(f"完整报告生成: {len(report)} 字符")
        return report

    def to_markdown_file(
        self,
        report: str,
        filename: Optional[str] = None,
    ) -> str:
        """将报告保存为 Markdown 文件

        Args:
            report: 报告文本
            filename: 文件名（不含路径），默认按日期生成

        Returns:
            文件完整路径
        """
        if filename is None:
            date_str = datetime.now().strftime('%Y%m%d')
            filename = f"strategy_briefing_{date_str}.md"

        file_path = os.path.join(self.output_dir, filename)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(report)

        logger.info(f"报告已保存: {file_path}")
        return file_path

    def to_html_email(self, report: str) -> str:
        """将 Markdown 报告转换为 HTML 邮件格式

        Args:
            report: Markdown 报告文本

        Returns:
            HTML 字符串（适用于邮件发送）
        """
        # 简单的 Markdown → HTML 转换
        import re

        html = report

        # 标题
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)

        # 粗体和斜体
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)

        # 表格简化 (保留为 pre 格式)
        html = re.sub(r'\|(.+)\|', r'<pre>|\1|</pre>', html)

        # 分隔线
        html = html.replace('---', '<hr>')

        # 换行
        html = html.replace('\n\n', '<br><br>')

        wrapper = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 720px; margin: 0 auto; padding: 20px; color: #1a1a1a;
               background: #f8f9fa; }}
        h1 {{ color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 8px; }}
        h2 {{ color: #2c5282; margin-top: 28px; }}
        h3 {{ color: #2d3748; }}
        pre {{ background: #edf2f7; padding: 10px; border-radius: 6px; overflow-x: auto; }}
        hr {{ border: 0; border-top: 1px solid #e2e8f0; margin: 24px 0; }}
        strong {{ color: #c53030; }}
        blockquote {{ border-left: 4px solid #ecc94b; margin: 0; padding: 8px 16px;
                    background: #fffff0; }}
    </style>
</head>
<body>
{html}
</body>
</html>"""

        logger.info(f"HTML 邮件生成: {len(wrapper)} 字符")
        return wrapper

    def to_telegram_message(self, report: str) -> str:
        """将报告转换为 Telegram 兼容的纯文本/轻度 Markdown 消息

        Telegram 支持有限的 MarkdownV2 格式。
        此方法生成简化版文本消息。

        Args:
            report: 完整 Markdown 报告

        Returns:
            Telegram 兼容的文本消息
        """
        lines = report.split('\n')
        telegram_lines = []

        for line in lines:
            # 跳过 HTML 标签
            if '<h1>' in line or '<h2>' in line or '<h3>' in line:
                continue
            if '<style>' in line or '</style>' in line:
                continue

            # 简化：去除 HTML 但保留内容
            clean = line.replace('<strong>', '*').replace('</strong>', '*')
            clean = clean.replace('<em>', '_').replace('</em>', '_')
            clean = clean.replace('<hr>', '――――――――――')

            if clean.strip():
                telegram_lines.append(clean)

        text = '\n'.join(telegram_lines)

        # Telegram 消息长度限制 4096
        if len(text) > 4000:
            text = text[:4000] + "\n\n... [truncated]"

        logger.info(f"Telegram 消息生成: {len(text)} 字符")
        return text

    def compose_degraded_mode_report(
        self,
        envelope: GatewayEnvelope,
        error_message: str = "",
    ) -> str:
        """生成降级模式报告（LLM 不可用时）

        直接从 Layer 2 JSON 生成简洁的纯文本摘要。

        Args:
            envelope: 网关信封
            error_message: 错误原因

        Returns:
            降级模式纯文本报告
        """
        from llm_inference.prompt_builder import PromptBuilder
        builder = PromptBuilder()
        summary = builder.build_degraded_mode_prompt(envelope)

        header = f"{self.branding} — Degraded Mode Summary\n{'=' * 50}\n"
        if error_message:
            header += f"LLM Error: {error_message}\n{'=' * 50}\n"

        return header + "\n" + summary
